project:
  type: website

website:
  title: "Computer Vision Paper Review"
  site-url: https://cv-review.patrickli.org/
  repo-url: https://github.com/TengMCing/computer_vision_review/
  repo-branch: main
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides/index.qmd
        text: Slides
      - href: about.qmd
        text: About me

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: source