project:
  type: website

website:
  title: "Computer Vision Paper Review"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides/index.qmd
        text: Slides
      - href: about.qmd
        text: About me

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

